[tool.poetry]
name = "app"
version = "0.0.1"
description = "FastAPI"
authors = ["Erdinc"]

[tool.poetry.dependencies]
python = "^3.8"
uvicorn = "~0.11.3"
fastapi = "~0.82.00"
python-multipart = "~0.0.5"
pydantic = {extras = ["email"], version = "~1.8.1"}